# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9e5e3eb758c21f2d050caa14734ec9ddc5805008e909722a20f4e47f7d8371b0fc2ac5157313dfe0a89597f2b146280280d11304c622cd1a0c7045152ffd821

test:
  secret_key_base: 30874e1eda872a440ab019ee5241bf8e0466a4be5397e34ffe6b3c34174c14caba2a5c51300e09a3fbd1f4724d048aaaf52bdfedf063af7f10c0c1ccf854482b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
